#!/bin/sh
#
# Just a handy script to run any apps under /classes.

java -cp classes:lib/neo4j-java-driver-1.3.0.jar:lib/intermine-client.jar:lib/intermine-pathquery.jar:lib/intermine-model.jar:lib/antlr-2.7.6-caching.jar:lib/commons-codec-1.9-sources.jar:lib/commons-io-1.2.jar:lib/commons-logging-1.1.1.jar:lib/json20110106.jar:lib/stax-api-1.0.jar:lib/commons-codec-1.9.jar:lib/commons-httpclient-3.0.jar:lib/commons-lang-2.6.jar:lib/log4j.jar:lib/stax-ri-1.0.jar $1 $2 $3 $4 $5 $6 $7 $8 $9
