MATCH (gene :Gene)


RETURN gene.primaryIdentifier,
gene_chromosome.primaryIdentifier,
gene_chromosome_sequenceontologyterm.identifier,
gene_chromosome_sequenceontologyterm_datasets.url,
gene_chromosome_sequenceontologyterm_datasets_publication.doi,
gene_chromosome_sequenceontologyterm_datasets_publication_authors.name
ORDER BY gene.primaryIdentifier ASC
